Expand AppData metadata, including screenshots.
flathub/com.valvesoftware.Steam pull request #37
Opened 2017-10-30 12:13 UTC by mavit

This additional information should make things look more appealing in, e.g, Gnome Software.

2017-10-30 12:32 UTC, TingPing requested changes

2017-10-30 12:32 UTC, TingPing commented on com.valvesoftware.Steam.appdata.xml
> +  <update_contact>https://github.com/flathub/com.valvesoftware.Steam/issues</update_contact>
The spec says this needs to be an email, feel free to make it `tingping_AT_fedoraproject.org`

2017-12-15 14:06 UTC, nedrichards commented
bot, build

2017-12-15 14:08 UTC, nedrichards commented
applied @TingPing's change and merging.

2017-12-15 14:08 UTC, merged